project_id = "bvieqoevqkwdkphubabt"

[functions.confirm-organisation-account]
verify_jwt = false

[functions.signup-organisation]
verify_jwt = false

[functions.send-report-via-notifications-api]
verify_jwt = false

[functions.generate-athlete-report]
verify_jwt = false

[functions.generate-ai-coach-insight]
verify_jwt = false

[functions.generate-programming-ai-summary]
verify_jwt = false

[functions.generate-force-plate-report]
verify_jwt = false

[functions.send-consent-email]
verify_jwt = false

[functions.compute-org-health-snapshots]
verify_jwt = false

[functions.generate-platform-alerts]
verify_jwt = false

[functions.fetch-google-sheet-csv]
verify_jwt = false

[functions.enrich-exercise]
verify_jwt = false

[functions.compute-client-rank-events]
verify_jwt = false

[functions.generate-golf-summary]
verify_jwt = false
