import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import notificationapi from 'npm:notificationapi-node-server-sdk'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

// Initialize NotificationsAPI
const notificationsApiKey = Deno.env.get('NOTIFICATIONS_API_KEY');
const notificationsDomainKey = Deno.env.get('NOTIFICATIONS_API_DOMAIN_KEY');

if (notificationsApiKey && notificationsDomainKey) {
  notificationapi.init(
    'n3g0q177rbzrr6riq8re90n1yc',
    notificationsApiKey,
    {
      baseURL: 'https://api.eu.notificationapi.com',
      domainKey: notificationsDomainKey
    }
  );
}

Deno.serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const { athlete_id, pdf_path } = await req.json();
    
    if (!athlete_id || !pdf_path) {
      return new Response(
        JSON.stringify({ error: 'athlete_id and pdf_path are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log(`Sending report for athlete_id: ${athlete_id}, pdf_path: ${pdf_path}`);

    // Fetch athlete data
    const { data: athlete, error: athleteError } = await supabaseClient
      .from('athletes_new')
      .select('*')
      .eq('id', athlete_id)
      .single();

    if (athleteError || !athlete) {
      console.error('Error fetching athlete:', athleteError);
      return new Response(
        JSON.stringify({ error: 'Athlete not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Prepare report date in DD/MM/YYYY format
    const today = new Date();
    const report_date = `${today.getDate().toString().padStart(2, '0')}/${(today.getMonth() + 1).toString().padStart(2, '0')}/${today.getFullYear()}`;

    // Resolve recipient email: prefer Athlete Credentials (athletes table), fallback to athletes_new
    let recipientEmail = athlete.email as string | null;
    try {
      // Try to find matching team ids for the textual team name
      let teamIds: string[] = [];
      if (athlete.team) {
        const { data: teams } = await supabaseClient
          .from('teams')
          .select('id')
          .ilike('name', `%${athlete.team}%`);
        teamIds = (teams || []).map((t: any) => t.id);
      }

      // Find athlete credentials by name (and optionally team)
      const { data: credCandidates } = await supabaseClient
        .from('athletes')
        .select('email,name,team_id')
        .ilike('name', `%${athlete.name}%`);

      const matched = (credCandidates || []).find((a: any) => a.email && (!teamIds.length || teamIds.includes(a.team_id)));
      if (matched?.email) recipientEmail = matched.email;
    } catch (e) {
      console.warn('Athlete credential email resolution failed, using athletes_new.email. Reason:', e);
    }

    console.log('Recipient email resolved to:', recipientEmail || '(none)');

    // Get the report content from the pdf_path (which contains the generated report)
    const reportContent = `Performance Report for ${athlete.name}

Team: ${athlete.team}
Report Date: ${report_date}
Testing Dates: ${athlete.testing_dates}

This report contains comprehensive performance analysis and recommendations for ${athlete.name}.

Generated by Force Plate Analytics Platform`;

    // Check if NotificationsAPI is configured
    if (!notificationsApiKey || !notificationsDomainKey) {
      console.error('NotificationsAPI not configured - missing API key or domain key');
      return new Response(
        JSON.stringify({ error: 'Email service not configured - missing NotificationsAPI keys' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('Sending report via NotificationsAPI...');
    
    try {
      await notificationapi.send({
        notificationId: 'athlete_report_email',
        user: {
          id: athlete.id,
          email: recipientEmail || athlete.email
        },
        mergeTags: {
          athlete_name: athlete.name,
          team_name: athlete.team,
          report_date: report_date,
          testing_dates: athlete.testing_dates,
          report_content: reportContent
        }
      });

      console.log('Report sent successfully via NotificationsAPI');

      return new Response(
        JSON.stringify({ 
          success: true, 
          message: 'Report sent successfully via NotificationsAPI',
          email: athlete.email,
          athlete_name: athlete.name,
          team_name: athlete.team
        }),
        { 
          status: 200, 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
        }
      );

    } catch (error) {
      console.error('Error sending email via NotificationsAPI:', error);
      return new Response(
        JSON.stringify({ 
          error: 'Failed to send email via NotificationsAPI', 
          details: error.message
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

  } catch (error) {
    console.error('Error in send-report-via-notifications-api function:', error);
    return new Response(
      JSON.stringify({ error: 'Internal server error', details: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});