import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { Resend } from 'npm:resend@2.0.0'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const { athlete_id, pdf_path } = await req.json();
    
    if (!athlete_id || !pdf_path) {
      return new Response(
        JSON.stringify({ error: 'athlete_id and pdf_path are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log(`Sending report for athlete_id: ${athlete_id}, pdf_path: ${pdf_path}`);

    // Fetch athlete data
    const { data: athlete, error: athleteError } = await supabaseClient
      .from('athletes_new')
      .select('*')
      .eq('id', athlete_id)
      .single();

    if (athleteError || !athlete) {
      console.error('Error fetching athlete:', athleteError);
      return new Response(
        JSON.stringify({ error: 'Athlete not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Prepare report date in DD/MM/YYYY format
    const today = new Date();
    const report_date = `${today.getDate().toString().padStart(2, '0')}/${(today.getMonth() + 1).toString().padStart(2, '0')}/${today.getFullYear()}`;

    // Get the report content from the pdf_path (which contains the generated report)
    const reportContent = `Performance Report for ${athlete.name}

Team: ${athlete.team}
Report Date: ${report_date}
Testing Dates: ${athlete.testing_dates}

This report contains comprehensive performance analysis and recommendations for ${athlete.name}.

Generated by Force Plate Analytics Platform`;

    // Check if Resend API key exists
    const resendApiKey = Deno.env.get('RESEND_API_KEY');
    if (!resendApiKey) {
      console.error('RESEND_API_KEY environment variable not set');
      return new Response(
        JSON.stringify({ error: 'Email service not configured - missing Resend API key' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('Sending report via Resend...');
    
    try {
      const resend = new Resend(resendApiKey);

      const emailResponse = await resend.emails.send({
        from: 'Force Plate Analytics <reports@resend.dev>',
        to: [athlete.email],
        subject: `Performance Report - ${athlete.name} (${athlete.team})`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #2563eb;">Performance Report</h1>
            <p><strong>Athlete:</strong> ${athlete.name}</p>
            <p><strong>Team:</strong> ${athlete.team}</p>
            <p><strong>Report Date:</strong> ${report_date}</p>
            <p><strong>Testing Dates:</strong> ${athlete.testing_dates}</p>
            
            <hr style="margin: 20px 0;">
            
            <h2 style="color: #374151;">Report Summary</h2>
            <p>This comprehensive performance analysis includes:</p>
            <ul>
              <li>Force plate metrics analysis</li>
              <li>Performance comparisons</li>
              <li>Training recommendations</li>
              <li>Progress tracking</li>
            </ul>
            
            <div style="background-color: #f3f4f6; padding: 15px; border-radius: 8px; margin: 20px 0;">
              <h3 style="margin-top: 0; color: #374151;">Report Content</h3>
              <pre style="white-space: pre-wrap; font-family: monospace; font-size: 12px;">${reportContent}</pre>
            </div>
            
            <p style="color: #6b7280; font-size: 14px;">
              Generated by Force Plate Analytics Platform
            </p>
          </div>
        `,
      });

      console.log('Email sent successfully via Resend:', emailResponse);

      return new Response(
        JSON.stringify({ 
          success: true, 
          message: 'Report sent successfully via email',
          email: athlete.email,
          athlete_name: athlete.name,
          team_name: athlete.team
        }),
        { 
          status: 200, 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
        }
      );

    } catch (error) {
      console.error('Error sending email via Resend:', error);
      return new Response(
        JSON.stringify({ 
          error: 'Failed to send email via Resend', 
          details: error.message
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

  } catch (error) {
    console.error('Error in send-report-via-notifications-api function:', error);
    return new Response(
      JSON.stringify({ error: 'Internal server error', details: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});